#!/bin/bash

check_exit_status() {
    
    if [ $? -eq 0 ]
    then 
        echo
        echo "Success"
        echo
    else
        echo
        echo "[ERROR] Process Failed!"
        echo

        read -p "The last command exited with an error. Exit script? (yes/no) " answer

        if [ "$answer" == "yes" ]
        then
            exit 1
        fi
    fi
}
greeting() {
    
    echo
    echo "Hello, $USER. Let's update this system."
    echo
}

update(){

    apt-get update;
    check_exit_status

    apt-get upgrade -y
    check_exit_status

    apt-get dist-upgrade -y;
    chcek_exit_status
}

housekeeping() {

    apt-get autoremove -y;
    check_exit_status

    apt-get autoclean -y;
    check_exit_status

    updatedb;
    check_exit_status
}

leave() {

    echo
    echo "--------------------"
    echo "- Update Complete! -"
    echo "--------------------"
    echo
    exit
}

greeting
update
housekeeping
leave
